### ISSUE TITLE
Auto lang detection

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#34]
Read the accepted language from the browser header. Either it is German (something wie a `de`) than the locale will be `de` otherwise it will be `en`.  Please have a look at https://github.com/smeevil/set_locale if that makes sense go for it otherwise use a different solution. Right now we only need the Accept-Language HTTP header variant.

**Comment by philipp-kempgen** [comment]
I can't even open the root page now.

```
animina-web-1  | [info] GET /
animina-web-1  | [debug] Processing with AniminaWeb.RootLive.register/2
animina-web-1  |   Parameters: %{}
animina-web-1  |   Pipelines: [:browser]
animina-web-1  | [info] Sent 500 in 73ms
animina-web-1  | [error] #PID<0.587.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.586.0>, stream id 1) terminated
animina-web-1  | Server: 0.0.0.0:4000 (http)
animina-web-1  | Request: GET /
animina-web-1  | ** (exit) an exception was raised:
animina-web-1  |     ** (CaseClauseError) no case clause matching: "de"
animina-web-1  |         (animina 0.1.0) lib/animina_web/plugs/language.ex:51: AniminaWeb.Plugs.AcceptLanguage.parse_language/1
animina-web-1  |         (animina 0.1.0) lib/animina_web/plugs/language.ex:16: AniminaWeb.Plugs.AcceptLanguage.call/2
animina-web-1  |         (animina 0.1.0) AniminaWeb.Router.browser/2
animina-web-1  |         (animina 0.1.0) lib/animina_web/router.ex:1: AniminaWeb.Router.__pipe_through0__/1
animina-web-1  |         (phoenix 1.7.11) lib/phoenix/router.ex:475: Phoenix.Router.__call__/5
animina-web-1  |         (animina 0.1.0) lib/animina_web/endpoint.ex:1: AniminaWeb.Endpoint.plug_builder_call/2
animina-web-1  |         (animina 0.1.0) deps/plug/lib/plug/debugger.ex:136: AniminaWeb.Endpoint."call (overridable 3)"/2
animina-web-1  |         (animina 0.1.0) lib/animina_web/endpoint.ex:1: AniminaWeb.Endpoint.call/2
animina-web-1  |         (phoenix 1.7.11) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
animina-web-1  |         (plug_cowboy 2.7.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
animina-web-1  |         (cowboy 2.10.0) /application/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
animina-web-1  |         (cowboy 2.10.0) /application/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
animina-web-1  |         (cowboy 2.10.0) /application/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
animina-web-1  |         (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

That's for `Accept-Language: de,en-US;q=0.7,en;q=0.3`.
In my Firefox, `intl.accept_languages` is set to the default value of "`de, en-US, en`".

It seems to work for any of these:

`Accept-Language: de-DE`
`Accept-Language: de-CH`
`Accept-Language: en-US`

i.e. xx-XX format, starting in "de" or "en".

I get an exception for `Accept-Language: fr-FR`:

```
animina-web-1  | [info] GET /
animina-web-1  | [debug] Processing with AniminaWeb.RootLive.register/2
animina-web-1  |   Parameters: %{}
animina-web-1  |   Pipelines: [:browser]
animina-web-1  | [info] Sent 500 in 37ms
animina-web-1  | [error] #PID<0.1445.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.1215.0>, stream id 14) terminated
animina-web-1  | Server: 0.0.0.0:4000 (http)
animina-web-1  | Request: GET /
animina-web-1  | ** (exit) an exception was raised:
animina-web-1  |     ** (CaseClauseError) no case clause matching: "fr-FR"
animina-web-1  |         (animina 0.1.0) lib/animina_web/plugs/language.ex:51: AniminaWeb.Plugs.AcceptLanguage.parse_language/1
animina-web-1  |         (animina 0.1.0) lib/animina_web/plugs/language.ex:16: AniminaWeb.Plugs.AcceptLanguage.call/2
animina-web-1  |         (animina 0.1.0) AniminaWeb.Router.browser/2
animina-web-1  |         (animina 0.1.0) lib/animina_web/router.ex:1: AniminaWeb.Router.__pipe_through0__/1
[...]
```

or for `Accept-Language: sr-Latn` (or `sr-Latn-ME`):

```

animina-web-1  | [info] GET /
animina-web-1  | [debug] Processing with AniminaWeb.RootLive.register/2
animina-web-1  |   Parameters: %{}
animina-web-1  |   Pipelines: [:browser]
animina-web-1  | [info] Sent 500 in 53ms
animina-web-1  | [error] #PID<0.1563.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.1479.0>, stream id 5) terminated
animina-web-1  | Server: 0.0.0.0:4000 (http)
animina-web-1  | Request: GET /
animina-web-1  | ** (exit) an exception was raised:
animina-web-1  |     ** (CaseClauseError) no case clause matching: "sr-Latn"
animina-web-1  |         (animina 0.1.0) lib/animina_web/plugs/language.ex:51: AniminaWeb.Plugs.AcceptLanguage.parse_language/1
animina-web-1  |         (animina 0.1.0) lib/animina_web/plugs/language.ex:16: AniminaWeb.Plugs.AcceptLanguage.call/2
animina-web-1  |         (animina 0.1.0) AniminaWeb.Router.browser/2
animina-web-1  |         (animina 0.1.0) lib/animina_web/router.ex:1: AniminaWeb.Router.__pipe_through0__/1
[...]
```

**Comment by philipp-kempgen** [comment]
- https://elixirforum.com/t/why-is-accept-languages-not-evaluated/34874
- https://elixirforum.com/t/is-there-an-hex-package-to-parse-accept-language-header/12161
- https://hexdocs.pm/ex_cldr_plugs/readme.html

**Comment by philipp-kempgen** [comment]
Also, do we want tests for these values?

**Comment by philipp-kempgen** [comment]
A language tag could also be something like „`en-cockney`“, „`i-navajo`“, „`x-klingon`“, „`tlh-Latn`“ or „`*`“. The code should handle them gracefully and fall back to a default language.

FWIW here's a really old implementation that even allows you to specify that amongst what the server has to offer the "en-UK" variant has a q(ality) of 1.0 while "de-DE" has a q of 0.8:
- https://github.com/philipp-kempgen/offer-accept-matcher
- https://github.com/philipp-kempgen/offer-accept-matcher/blob/master/lib/offer_accept_matcher.rb?ts=4

It didn't care about the special meaning of "i-" and "x-" prefixes though.

**Comment by briankariuki** [comment]
> A language tag could also be something like „`en-cockney`“, „`i-navajo`“, „`x-klingon`“, „`tlh-Latn`“ or „`*`“. The code should handle them gracefully and fall back to a default language.
> 
> FWIW here's a really old implementation that even allows you to specify that amongst what the server has to offer the "en-UK" variant has a q(ality) of 1.0 while "de-DE" has a q of 0.8:
> 
> * https://github.com/philipp-kempgen/offer-accept-matcher
> * https://github.com/philipp-kempgen/offer-accept-matcher/blob/master/lib/offer_accept_matcher.rb?ts=4
> 
> It didn't care about the special meaning of "i-" and "x-" prefixes though.

I've fixed this in a pull request. We can now parse any language other than english and german.
