### ISSUE TITLE
GenServer {Oban.Registry, {Oban, {:producer, "default"}}} terminating

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#450]
I constantly get this error and before I'll fiddle around with my database config: Please make sure that this is not a programming bug.

```elixir
[error] GenServer {Oban.Registry, {Oban, {:producer, "default"}}} terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1826ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (db_connection 2.6.0) lib/db_connection.ex:1059: DBConnection.transaction/3
    (oban 2.17.10) lib/oban/engine.ex:223: anonymous fn/4 in Oban.Engine.fetch_jobs/3
    (oban 2.17.10) lib/oban/engine.ex:319: anonymous fn/3 in Oban.Engine.with_span/4
    (telemetry 1.2.1) /Users/stefan/GitHub/animina/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.17.10) lib/oban/queue/producer.ex:245: Oban.Queue.Producer.start_jobs/1
    (oban 2.17.10) lib/oban/queue/producer.ex:236: anonymous fn/2 in Oban.Queue.Producer.dispatch/1
    (telemetry 1.2.1) /Users/stefan/GitHub/animina/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.17.10) lib/oban/queue/producer.ex:235: Oban.Queue.Producer.dispatch/1
    (oban 2.17.10) lib/oban/queue/producer.ex:168: Oban.Queue.Producer.handle_info/2
    (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: :dispatch
State: %Oban.Queue.Producer{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Basic, get_dynamic_repo: nil, insert_trigger: true, log: false, name: Oban, node: "Bimini", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Plugins.Lifeline, [rescue_after: 1800000]}, {Oban.Plugins.Pruner, [max_age: 5184000]}, {Oban.Plugins.Cron, [crontab: [{"* * * * *", Animina.Accounts.Photo.AshOban.Scheduler.Process, []}]]}], prefix: "public", queues: [default: [limit: 10], photos: [limit: 10]], repo: Animina.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, foreman: {:via, Registry, {Oban.Registry, {Oban, {:foreman, "default"}}}}, meta: %{name: Oban, node: "Bimini", queue: "default", started_at: ~U[2024-05-16 14:36:56.442119Z], limit: 10, updated_at: ~U[2024-05-16 14:36:56.442127Z], uuid: "878121c9-e3a6-43d5-a2fe-859478e21717", paused: false, refresh_interval: 30000}, name: {:via, Registry, {Oban.Registry, {Oban, {:producer, "default"}}}}, dispatch_timer: #Reference<0.1995213965.4249878531.219672>, refresh_timer: #Reference<0.1995213965.4249878531.219663>, dispatch_cooldown: 5, running: %{}}
```

**Comment by briankariuki** [comment]
@wintermeyer  How are you running  your postgres database? Via docker or as a service installed?

**Comment by wintermeyer** [comment]
> @wintermeyer How are you running your postgres database? Via docker or as a service installed?

Via service installed (with Homebrew). I am not a fan of Docker.

**Comment by briankariuki** [comment]
@wintermeyer Do you still encounter this issue? With the change introduced in #451, this should be resolved now.
