### ISSUE TITLE
Error running AshOban scheduler

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#472]
I get this error:

```elixir
[error] Error running AshOban scheduler Elixir.Animina.Accounts.Photo.AshOban.Scheduler.Process.
** (Ash.Error.Forbidden) Forbidden

* forbidden
  (elixir 1.16.0) lib/process.ex:860: Process.info/2
  (ash 2.21.14) lib/ash/error/exception.ex:59: Ash.Error.Forbidden.Policy."exception (overridable 2)"/1
  (ash 2.21.14) lib/ash/error/forbidden/policy.ex:28: Ash.Error.Forbidden.Policy.exception/1
  (ash 2.21.14) lib/ash/policy/authorizer/authorizer.ex:1389: Ash.Policy.Authorizer.strict_check_result/2
  (ash 2.21.14) lib/ash/policy/authorizer/authorizer.ex:482: Ash.Policy.Authorizer.strict_check/2
  (ash 2.21.14) lib/ash/api/api.ex:1057: anonymous fn/6 in Ash.Api.run_check/4
  (elixir 1.16.0) lib/enum.ex:4842: Enumerable.List.reduce/3
  (elixir 1.16.0) lib/enum.ex:2582: Enum.reduce_while/3
  (ash 2.21.14) lib/ash/api/api.ex:1054: Ash.Api.run_check/4
  (ash 2.21.14) lib/ash/api/api.ex:904: Ash.Api.can/4
  (ash 2.21.14) lib/ash/actions/read/read.ex:774: Ash.Actions.Read.authorize_query/2
  (ash 2.21.14) lib/ash/actions/read/read.ex:326: anonymous fn/5 in Ash.Actions.Read.do_read/4
  (ash 2.21.14) lib/ash/engine/engine.ex:514: anonymous fn/4 in Ash.Engine.async/2
  (elixir 1.16.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
  (elixir 1.16.0) lib/task/supervised.ex:36: Task.Supervised.reply/4
    (elixir 1.16.0) lib/process.ex:860: Process.info/2
    (ash 2.21.14) lib/ash/error/exception.ex:59: Ash.Error.Forbidden.exception/1
    (ash 2.21.14) lib/ash/error/error.ex:602: Ash.Error.choose_error/2
    (ash 2.21.14) lib/ash/error/error.ex:260: Ash.Error.to_error_class/2
    (ash 2.21.14) lib/ash/actions/read/read.ex:292: Ash.Actions.Read.do_run/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:50: anonymous fn/3 in Ash.Actions.Read.run/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:49: Ash.Actions.Read.run/3
    (ash 2.21.14) lib/ash/api/api.ex:2567: Ash.Api.read!/3
    (ash 2.21.14) lib/ash/actions/read/stream.ex:45: anonymous fn/5 in Ash.Actions.Read.Stream.do_stream/4
    (elixir 1.16.0) lib/stream.ex:1626: Stream.do_resource/5
    (elixir 1.16.0) lib/stream.ex:1828: Enumerable.Stream.do_each/4
    (elixir 1.16.0) lib/enum.ex:707: Enum.count/1
    (animina 0.1.0) deps/ash_oban/lib/transformers/define_schedulers.ex:153: Animina.Accounts.Photo.AshOban.Scheduler.Process.insert/1
    (animina 0.1.0) deps/ash_oban/lib/transformers/define_schedulers.ex:223: Animina.Accounts.Photo.AshOban.Scheduler.Process.perform/1
    (oban 2.17.10) lib/oban/queue/executor.ex:129: Oban.Queue.Executor.perform/1
    (oban 2.17.10) lib/oban/queue/executor.ex:74: Oban.Queue.Executor.call/1
    (elixir 1.16.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.16.0) lib/task/supervised.ex:36: Task.Supervised.reply/4
```

**Comment by briankariuki** [comment]
I think this is related to policies. @MICHAELMUNAVU83 Did you add policies to the photos resource. If so you need to add a bypass for ash_oban like this

```
policies do
   bypass AshOban.Checks.AshObanInteraction do
      authorize_if always()
   end

   // Other policies
end

```

**Comment by MICHAELMUNAVU83** [comment]
It is not policies..it was an error in the transition, I have found it and
I am working on fixing it
