### ISSUE TITLE
could not lookup Ecto repo Animina.Repo

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#643]
What I did:

```bash
mix ecto.reset
mix seed_demo_system
```

The problem:

```elixir
** (RuntimeError) could not lookup Ecto repo Animina.Repo because it was not started or it does not exist
    (ecto 3.11.2) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1
    (ecto 3.11.2) lib/ecto/repo/transaction.ex:39: Ecto.Repo.Transaction.in_transaction?/1
    (ash 2.21.14) lib/ash/engine/engine.ex:145: Ash.Engine.task_with_timeout/5
    (ash 2.21.14) lib/ash/actions/read/read.ex:537: Ash.Actions.Read.maybe_in_transaction/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:227: Ash.Actions.Read.do_run/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:50: anonymous fn/3 in Ash.Actions.Read.run/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:49: Ash.Actions.Read.run/3
    (ash 2.21.14) lib/ash/actions/read/relationships.ex:467: anonymous fn/3 in Ash.Actions.Read.Relationships.do_fetch_related_records/3
    (elixir 1.16.3) lib/enum.ex:1708: anonymous fn/3 in Enum.map/2
    (elixir 1.16.3) lib/enum.ex:4396: anonymous fn/3 in Enum.map/2
    (elixir 1.16.3) lib/stream.ex:1816: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/stream.ex:1828: Enumerable.Stream.do_each/4
    (elixir 1.16.3) lib/enum.ex:4396: Enum.map/2
    (ash 2.21.14) lib/ash/actions/read/relationships.ex:39: Ash.Actions.Read.Relationships.fetch_related_records/2
    (ash 2.21.14) lib/ash/actions/read/relationships.ex:23: Ash.Actions.Read.Relationships.load/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:248: Ash.Actions.Read.do_run/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:50: anonymous fn/3 in Ash.Actions.Read.run/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:49: Ash.Actions.Read.run/3
    (ash 2.21.14) lib/ash/actions/read/relationships.ex:467: anonymous fn/3 in Ash.Actions.Read.Relationships.do_fetch_related_records/3
```

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I personally get this
```
** (HTTPoison.Error) :timeout
    (httpoison 2.2.1) lib/httpoison/base.ex:451: HTTPoison.request!/5
    (animina 0.1.0) lib/mix/tasks/seed_demo_system.ex:607: Mix.Tasks.SeedDemoSystem.download_photo/2
    (animina 0.1.0) lib/mix/tasks/seed_demo_system.ex:728: Mix.Tasks.SeedDemoSystem.pick_a_random_photo/1
    (animina 0.1.0) lib/mix/tasks/seed_demo_system.ex:678: Mix.Tasks.SeedDemoSystem.create_random_stories/5
    (animina 0.1.0) lib/mix/tasks/seed_demo_system.ex:331: Mix.Tasks.SeedDemoSystem.create_demo_user/1
    (elixir 1.16.3) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (animina 0.1.0) lib/mix/tasks/seed_demo_system.ex:27: Mix.Tasks.SeedDemoSystem.run/1
    (mix 1.16.3) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.3) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /Users/mac/.asdf/installs/elixir/1.16.3/bin/mix:2: (file)
    (elixir 1.16.3) lib/code.ex:1489: Code.require_file/2
```

Is your mix task making it past this point?

**Comment by wintermeyer** [comment]
I get this error:

```elixir
[error] Task #PID<0.1392.0> started from Animina.GenServers.PhotoConsumerSupervisor terminating
** (Ash.Error.Unknown) Unknown Error

* ** (CaseClauseError) no case clause matching: {:ok, #Animina.Accounts.Photo<story: #Ash.NotLoaded<:relationship, field: :story>, user: #Ash.NotLoaded<:relationship, field: :user>, __meta__: #Ecto.Schema.Metadata<:loaded, "photos">, id: "7079b2ea-542c-46b1-b41e-bbb25aa7bb02", filename: "8a00ddbe-1afd-4dc2-b5de-3d4615fc9e5b.png", original_filename: "8a00ddbe-1afd-4dc2-b5de-3d4615fc9e5b.png", mime: "image/png", size: 4311060, ext: "png", dimensions: nil, error: "unknown error: {:noproc, {Nx.Serving, :distributed_batched_run, [NsfwDetectionServing, %StbImage{data: <<192, 161, 129, 192, 161, 127, 193, 161, 126, 193, 162, 129, 192, 162, 130, 191, 159, 126, 193, 162, 127, 193, 160, 127, 194, 161, 127, 192, 161, 128, 192, 161, 130, 192, 161, 130, 192, 162, 129, 193, 162, 130, ...>>, shape: {336, 224, 3}, type: {:u, 8}}, [retries: 3]]}}", error_state: "pending_review", state: :error, created_at: ~U[2024-06-10 08:45:54.382150Z], updated_at: ~U[2024-06-10 08:45:55.787361Z], user_id: "49a9a061-e0eb-43da-a2ab-58f9a22f095d", story_id: nil, aggregates: %{}, calculations: %{}, ...>, %{}}
  (ash 2.21.14) lib/ash/actions/update/update.ex:356: Ash.Actions.Update.commit/3
  (ash 2.21.14) lib/ash/actions/update/update.ex:89: Ash.Actions.Update.do_run/4
  (ash 2.21.14) lib/ash/actions/update/update.ex:50: Ash.Actions.Update.run/4
  (animina 0.1.0) lib/animina/accounts/accounts.ex:1: Animina.Accounts.update/2
  (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (ash 2.21.14) lib/ash/actions/update/update.ex:356: Ash.Actions.Update.commit/3
    (ash 2.21.14) lib/ash/actions/update/update.ex:89: Ash.Actions.Update.do_run/4
    (ash 2.21.14) lib/ash/actions/update/update.ex:50: Ash.Actions.Update.run/4
    (animina 0.1.0) lib/animina/accounts/accounts.ex:1: Animina.Accounts.update/2
    (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<0.6262360/0 in Animina.GenServers.PhotoConsumer.start_link/1>
    Args: []
```

And at the end:

```elixir
[notice] Application animina exited: shutdown
** (RuntimeError) could not lookup Ecto repo Animina.Repo because it was not started or it does not exist
    (ecto 3.11.2) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1
    (ecto 3.11.2) lib/ecto/repo/transaction.ex:39: Ecto.Repo.Transaction.in_transaction?/1
    (ash 2.21.14) lib/ash/engine/engine.ex:145: Ash.Engine.task_with_timeout/5
    (ash 2.21.14) lib/ash/actions/read/read.ex:537: Ash.Actions.Read.maybe_in_transaction/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:227: Ash.Actions.Read.do_run/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:50: anonymous fn/3 in Ash.Actions.Read.run/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:49: Ash.Actions.Read.run/3
    (ash 2.21.14) lib/ash/actions/read/relationships.ex:467: anonymous fn/3 in Ash.Actions.Read.Relationships.do_fetch_related_records/3
    (elixir 1.16.3) lib/enum.ex:1708: anonymous fn/3 in Enum.map/2
    (elixir 1.16.3) lib/enum.ex:4396: anonymous fn/3 in Enum.map/2
    (elixir 1.16.3) lib/stream.ex:1816: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/stream.ex:1828: Enumerable.Stream.do_each/4
    (elixir 1.16.3) lib/enum.ex:4396: Enum.map/2
    (ash 2.21.14) lib/ash/actions/read/relationships.ex:39: Ash.Actions.Read.Relationships.fetch_related_records/2
    (ash 2.21.14) lib/ash/actions/read/relationships.ex:23: Ash.Actions.Read.Relationships.load/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:248: Ash.Actions.Read.do_run/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:50: anonymous fn/3 in Ash.Actions.Read.run/3
    (ash 2.21.14) lib/ash/actions/read/read.ex:49: Ash.Actions.Read.run/3
    (ash 2.21.14) lib/ash/api/api.ex:2567: Ash.Api.read!/3
```

**Comment by MICHAELMUNAVU83** [comment]
Hey @wintermeyer  , mine works , but takes a lot of time , 15-25 minutes long.
In the mix task , on line 607 , change it to
```
 %HTTPoison.Response{body: body} = IO.inspect HTTPoison.get!(url,[], [timeout: 50_000, recv_timeout: 50_000])
```

And advise if it works now .

**Comment by wintermeyer** [comment]
Now an other problem:

```elixir
[error] Task #PID<0.1350.0> started from Animina.GenServers.PhotoConsumerSupervisor terminating
** (Ash.Error.Unknown) Unknown Error

* ** (CaseClauseError) no case clause matching: {:ok, #Animina.Accounts.Photo<story: #Ash.NotLoaded<:relationship, field: :story>, user: #Ash.NotLoaded<:relationship, field: :user>, __meta__: #Ecto.Schema.Metadata<:loaded, "photos">, id: "c5067155-13bf-4b8c-936b-6fd69549104a", filename: "1ba901f0-b109-49dd-b280-5e407dd9b3e7.png", original_filename: "1ba901f0-b109-49dd-b280-5e407dd9b3e7.png", mime: "image/png", size: 4311060, ext: "png", dimensions: nil, error: "unknown error: {:noproc, {Nx.Serving, :distributed_batched_run, [NsfwDetectionServing, %StbImage{data: <<192, 161, 129, 192, 161, 127, 193, 161, 126, 193, 162, 129, 192, 162, 130, 191, 159, 126, 193, 162, 127, 193, 160, 127, 194, 161, 127, 192, 161, 128, 192, 161, 130, 192, 161, 130, 192, 162, 129, 193, 162, 130, ...>>, shape: {336, 224, 3}, type: {:u, 8}}, [retries: 3]]}}", error_state: "pending_review", state: :error, created_at: ~U[2024-06-10 12:32:51.256604Z], updated_at: ~U[2024-06-10 12:32:51.961854Z], user_id: "cd2775c5-d5f6-4d4f-a526-570668aa9bb0", story_id: nil, aggregates: %{}, calculations: %{}, ...>, %{}}
  (ash 2.21.14) lib/ash/actions/update/update.ex:356: Ash.Actions.Update.commit/3
  (ash 2.21.14) lib/ash/actions/update/update.ex:89: Ash.Actions.Update.do_run/4
  (ash 2.21.14) lib/ash/actions/update/update.ex:50: Ash.Actions.Update.run/4
  (animina 0.1.0) lib/animina/accounts/accounts.ex:1: Animina.Accounts.update/2
  (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (ash 2.21.14) lib/ash/actions/update/update.ex:356: Ash.Actions.Update.commit/3
    (ash 2.21.14) lib/ash/actions/update/update.ex:89: Ash.Actions.Update.do_run/4
    (ash 2.21.14) lib/ash/actions/update/update.ex:50: Ash.Actions.Update.run/4
    (animina 0.1.0) lib/animina/accounts/accounts.ex:1: Animina.Accounts.update/2
    (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<0.6262360/0 in Animina.GenServers.PhotoConsumer.start_link/1>
    Args: []
[info] Postgrex.Protocol (#PID<0.509.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1360.0> exited
[info] Postgrex.Protocol (#PID<0.515.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1387.0> exited
[info] Postgrex.Protocol (#PID<0.508.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1378.0> exited
[info] Postgrex.Protocol (#PID<0.514.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1388.0> exited
```

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  just realized I cannot test this as I do not have the hardware to run the ML Stuff.
@briankariuki  , kindly assist

**Comment by briankariuki** [comment]
I think what is happening is the photo genserver starts before the NSFWServing has finished loading. And then it queues a photo for processing, which gets to the NSFW detection step and fails because the process has not yet been started. 

Hence the {:noproc, _} error.

A fix for this is to move the photo genserver supervision children after the NSFWServing

**Comment by wintermeyer** [comment]
Good enough or do you need more?

<img width="981" alt="Bildschirmfoto 2024-06-10 um 19 40 12" src="https://github.com/animina-dating/animina/assets/69770/6a260675-7b30-4ab6-a5a1-630eeaa8c2cd">

**Comment by briankariuki** [comment]
> Good enough or do you need more?
> 
> <img alt="Bildschirmfoto 2024-06-10 um 19 40 12" width="981" src="https://private-user-images.githubusercontent.com/69770/338287540-6a260675-7b30-4ab6-a5a1-630eeaa8c2cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDE1NjIsIm5iZiI6MTcxODA0MTI2MiwicGF0aCI6Ii82OTc3MC8zMzgyODc1NDAtNmEyNjA2NzUtN2IzMC00YWI2LWE1YTEtNjMwZWVhYThjMmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE3NDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNDI4MGRiZWNiZTczMDliMjYzZjM3OGYxMjk5OGZiNTAzM2RkNjQzZjU3YzFhMGQwMzAxMDA3ZDlhNTVhYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W6nFLcMsPwBqWGD5yxDLmR1Zd426Gbz36zwCieOgJhQ">

This will do
