### ISSUE TITLE
I can't upload an avatar photo on production

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#858]
@MICHAELMUNAVU83 Any idea?

```elixir
2024-08-13T10:43:45.789481+02:00 bremen2 animina[377481]:   Parameters: %{"token" => "SFMyNTY.g2gDaAJhBXQAAAADdwNwaWRYdw9hbmltaW5hQGJyZW1lbjIAABYOAAAAAGa1EKZ3A3JlZmgCbQAAABRwaHgtRi1zOUJMaHc0SEF0MVFPQ20AAAABMHcDY2lkdwNuaWxuBgDVVOhKkQFiAAFRgA.8jFJW2zQWRoHYw7pS0-e_b9Gu0y0bFqVQ7A75n7iWis"}
2024-08-13T10:43:47.451211+02:00 bremen2 animina[377481]: 10:43:47.444 [error] GenServer #PID<0.5646.0> terminating
2024-08-13T10:43:47.451415+02:00 bremen2 animina[377481]: ** (Ash.Error.Unknown) Unknown Error
2024-08-13T10:43:47.451511+02:00 bremen2 animina[377481]: * %File.Error{reason: nil, path: nil, action: ""}
2024-08-13T10:43:47.451600+02:00 bremen2 animina[377481]:   (mogrify 0.9.3) lib/mogrify.ex:13: Mogrify.open/1
2024-08-13T10:43:47.451684+02:00 bremen2 animina[377481]:   (animina 20240813.11030.117) lib/animina/accounts/resources/photo.ex:271: Animina.Accounts.Photo.resize_image/3
2024-08-13T10:43:47.451782+02:00 bremen2 animina[377481]:   (animina 20240813.11030.117) lib/animina/accounts/resources/photo.ex:261: anonymous fn/2 in Animina.Accounts.Photo.resize_image/1
2024-08-13T10:43:47.451865+02:00 bremen2 animina[377481]:   (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
2024-08-13T10:43:47.451945+02:00 bremen2 animina[377481]:   (animina 20240813.11030.117) lib/animina/accounts/resources/photo.ex:175: Animina.Accounts.Photo.change_after_action_0_generated_F26C32F8FCFF0724F6DFDB031FDE6017/3
2024-08-13T10:43:47.452027+02:00 bremen2 animina[377481]:   (ash 3.3.3) lib/ash/changeset/changeset.ex:3666: anonymous fn/2 in Ash.Changeset.run_after_actions/3
2024-08-13T10:43:47.452108+02:00 bremen2 animina[377481]:   (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
2024-08-13T10:43:47.452180+02:00 bremen2 animina[377481]:   (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
2024-08-13T10:43:47.452252+02:00 bremen2 animina[377481]:     (mogrify 0.9.3) lib/mogrify.ex:13: Mogrify.open/1
2024-08-13T10:43:47.452330+02:00 bremen2 animina[377481]:     (animina 20240813.11030.117) lib/animina/accounts/resources/photo.ex:271: Animina.Accounts.Photo.resize_image/3
2024-08-13T10:43:47.452409+02:00 bremen2 animina[377481]:     (animina 20240813.11030.117) lib/animina/accounts/resources/photo.ex:261: anonymous fn/2 in Animina.Accounts.Photo.resize_image/1
2024-08-13T10:43:47.452487+02:00 bremen2 animina[377481]:     (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
2024-08-13T10:43:47.452566+02:00 bremen2 animina[377481]:     (animina 20240813.11030.117) lib/animina/accounts/resources/photo.ex:175: Animina.Accounts.Photo.change_after_action_0_generated_F26C32F8FCFF0724F6DFDB031FDE6017/3
2024-08-13T10:43:47.452645+02:00 bremen2 animina[377481]:     (ash 3.3.3) lib/ash/changeset/changeset.ex:3666: anonymous fn/2 in Ash.Changeset.run_after_actions/3
2024-08-13T10:43:47.452723+02:00 bremen2 animina[377481]:     (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
2024-08-13T10:43:47.452809+02:00 bremen2 animina[377481]:     (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
2024-08-13T10:43:47.452889+02:00 bremen2 animina[377481]: Last message: %Phoenix.Socket.Message{topic: "lv:phx-F-s9AsAD0kIKvAED", event: "event", payload: %{"event" => "submit_photo", "type" => "form", "value" => "photo%5Buser_id%5D=c1996c66-8134-410a-8dbe-71cd9e8c4009&photo%5Bfilename%5D=90d3cb24-65b5-451c-8a86-7615c201b06b.jpg&photo%5Boriginal_filename%5D=IMG_8927.jpeg&photo%5Bext%5D=jpg&photo%5Bmime%5D=image%2Fjpeg&photo%5Bsize%5D=2771554"}, ref: "114", join_ref: "12"}
```

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I once experienced this when I did not have write access to the folder .
https://askubuntu.com/questions/265381/how-to-make-a-directory-permanently-writable

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 Which folder is used to write the files?

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , It seems it is failing at resizing images , kindly confirm if the photo is uploaded , if it is , the issue may be permissions in creating the `/uploads/optimized` folder.

Here , we create the folders , this is where I think the issue might be
```

defp create_optimized_folder_if_not_exists do
    for type <- ["thumbnail", "normal", "big"] do
      case File.mkdir_p("priv/static/uploads/optimized/#{type}") do
        :ok -> :ok
        _ -> :error
      end
    end
  end
```

A fix would be manually , in `/uploads` create subdirectories `/uploads/optimized/big` , `/uploads/optimized/normal` and `/uploads/optimized/thumbnail`

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 Please add something like 

```elixir
        {:error, reason} -> 
          Logger.error("Failed to create directory #{path}: #{reason}")
          {:error, reason}
```

to the code so that I can see the problem in the log files.

**Comment by wintermeyer** [comment]
I can't find the above error message in the current version:

```elixir
2024-08-13T12:40:04.752494+02:00 bremen2 animina[385659]:   Parameters: %{"token" => "SFMyNTY.g2gDaAJhBXQAAAADdwNwaWRYdw9hbmltaW5hQGJyZW1lbjIAABW5AAAAAGa1EKh3A3JlZmgCbQAAABRwaHgtRi10RGxxXzE3SlhmYVEyRG0AAAABMHcDY2lkdwNuaWxuBgBt0lJLkQFiAAFRgA.3BhtzOVVdS2tk5nKckVy_eBHwNAqOIJGg-EoBlOzisM"}
2024-08-13T12:40:06.884080+02:00 bremen2 animina[385659]: 12:40:06.878 [error] GenServer #PID<0.5561.0> terminating
2024-08-13T12:40:06.884253+02:00 bremen2 animina[385659]: ** (Ash.Error.Unknown) Unknown Error
2024-08-13T12:40:06.884326+02:00 bremen2 animina[385659]: * %File.Error{reason: nil, path: nil, action: ""}
2024-08-13T12:40:06.884382+02:00 bremen2 animina[385659]:   (mogrify 0.9.3) lib/mogrify.ex:13: Mogrify.open/1
2024-08-13T12:40:06.884437+02:00 bremen2 animina[385659]:   (animina 20240813.11205.114) lib/animina/accounts/resources/photo.ex:274: Animina.Accounts.Photo.resize_image/3
2024-08-13T12:40:06.884499+02:00 bremen2 animina[385659]:   (animina 20240813.11205.114) lib/animina/accounts/resources/photo.ex:264: anonymous fn/2 in Animina.Accounts.Photo.resize_image/1
2024-08-13T12:40:06.884561+02:00 bremen2 animina[385659]:   (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
2024-08-13T12:40:06.884623+02:00 bremen2 animina[385659]:   (animina 20240813.11205.114) lib/animina/accounts/resources/photo.ex:175: Animina.Accounts.Photo.change_after_action_0_generated_F26C32F8FCFF0724F6DFDB031FDE6017/3
2024-08-13T12:40:06.884683+02:00 bremen2 animina[385659]:   (ash 3.3.3) lib/ash/changeset/changeset.ex:3666: anonymous fn/2 in Ash.Changeset.run_after_actions/3
2024-08-13T12:40:06.884743+02:00 bremen2 animina[385659]:   (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
2024-08-13T12:40:06.884796+02:00 bremen2 animina[385659]:   (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
2024-08-13T12:40:06.884850+02:00 bremen2 animina[385659]:     (mogrify 0.9.3) lib/mogrify.ex:13: Mogrify.open/1
2024-08-13T12:40:06.884904+02:00 bremen2 animina[385659]:     (animina 20240813.11205.114) lib/animina/accounts/resources/photo.ex:274: Animina.Accounts.Photo.resize_image/3
2024-08-13T12:40:06.884965+02:00 bremen2 animina[385659]:     (animina 20240813.11205.114) lib/animina/accounts/resources/photo.ex:264: anonymous fn/2 in Animina.Accounts.Photo.resize_image/1
2024-08-13T12:40:06.885036+02:00 bremen2 animina[385659]:     (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
2024-08-13T12:40:06.885102+02:00 bremen2 animina[385659]:     (animina 20240813.11205.114) lib/animina/accounts/resources/photo.ex:175: Animina.Accounts.Photo.change_after_action_0_generated_F26C32F8FCFF0724F6DFDB031FDE6017/3
2024-08-13T12:40:06.885163+02:00 bremen2 animina[385659]:     (ash 3.3.3) lib/ash/changeset/changeset.ex:3666: anonymous fn/2 in Ash.Changeset.run_after_actions/3
2024-08-13T12:40:06.885219+02:00 bremen2 animina[385659]:     (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
2024-08-13T12:40:06.885275+02:00 bremen2 animina[385659]:     (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
2024-08-13T12:40:06.885339+02:00 bremen2 animina[385659]: Last message: %Phoenix.Socket.Message{topic: "lv:phx-F-tDlgUWuIZShQWC", event: "event", payload: %{"event" => "submit_photo", "type" => "form", "value" => "photo%5Buser_id%5D=c61fea56-7c9a-4437-ac35-77d172fe401b&photo%5Bfilename%5D=fd9d7148-758d-433a-b1a4-414449ca9c68.jpg&photo%5Boriginal_filename%5D=IMG_8927.jpeg&photo%5Bext%5D=jpg&photo%5Bmime%5D=image%2Fjpeg&photo%5Bsize%5D=2771554"}, ref: "106", join_ref: "12"}
```

@MICHAELMUNAVU83 Please try to create an account on production and have a look at `/var/log/syslog`

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer okay...let me do so.
Kindly confirm for me if on the production server there is an `uploads` folder , 
seems Mogrify can't open the file because it does not exist.
When pushing to prod ..if we reclone the system, we do not do so with the `uploads` 
folder so this might be it

**Comment by wintermeyer** [comment]
I created an `uploads` folder manually:

```bash
animina@bremen2:~/bin/animina/_build/prod/rel/animina/lib/animina-20240813.11234.152/priv/static/uploads$ tree
.
├── 077b10a2-1582-47de-a6a4-b20cabca75af.jpg
├── 3c05ed38-ce44-4493-a351-bafac30d4a99.jpg
├── 8076298d-f287-4f3f-96b8-4ce4b9bc6d56.jpg
└── optimized
    ├── big
    ├── normal
    └── thumbnail
```

It still doesn't work. 

Please try to start a copy of the application within your user's home directory and use SSH tunnel to connect it to your local browser. Test what happens. I only see these errors:

```elixir
2024-08-13T14:14:30.871400+02:00 bremen2 animina[389919]: ** (Ash.Error.Unknown) Unknown Error
2024-08-13T14:14:30.871503+02:00 bremen2 animina[389919]: * %File.Error{reason: nil, path: nil, action: ""}
2024-08-13T14:14:30.871572+02:00 bremen2 animina[389919]:   (mogrify 0.9.3) lib/mogrify.ex:13: Mogrify.open/1
```

**Comment by MICHAELMUNAVU83** [comment]
I started this @wintermeyer  , the image upload , but there is a bug that prevents the optimized image from being created.
I have made this fix in the next PR , kindly confirm if you merge it ,if it works

**Comment by wintermeyer** [comment]
```elixir
2024-08-14T09:32:29.032907+02:00 bremen2 animina[444838]: ** (File.CopyError) could not copy from "/tmp/plug-1723-60p6/live_view_upload-1723620747-221875197470-2" to "/home/animina/bin/animina/_build/prod/rel/animina/lib/animina-20240814.10659.107/priv/static/uploads/7ef24ce9-6a09-4505-9c80-9ae637fa1401.jpg": no such file or directory
```

Let me have a look at this directory.

**Comment by MICHAELMUNAVU83** [comment]
Aah , it might be because we are using `mix release` in prod , that is why on other environments it works well

**Comment by wintermeyer** [comment]
```elixir
2024-08-14T10:22:33.765307+02:00 bremen2 animina[460865]: 10:22:33.764 [info] JOINED lvu:0 in 1ms
2024-08-14T10:22:33.766134+02:00 bremen2 animina[460865]:   Parameters: %{"token" => "SFMyNTY.g2gDaAJhBXQAAAADdwNwaWRYdw9hbmltaW5hQGJyZW1lbjIAABZHAAAAAGa1ELB3A3JlZmgCbQAAABRwaHgtRi11S3BaaHlZVGlTWlFhQm0AAAABMHcDY2lkdwNuaWxuBgD_R_tPkQFiAAFRgA.8PviN0Shcqw6c2UWQXwP-61J8gna4Wg2L9Ab9PeSfc4"}
2024-08-14T10:22:35.416432+02:00 bremen2 animina[460865]: 10:22:35.410 [error] GenServer #PID<0.5703.0> terminating
2024-08-14T10:22:35.416580+02:00 bremen2 animina[460865]: ** (Ash.Error.Unknown) Unknown Error
2024-08-14T10:22:35.416611+02:00 bremen2 animina[460865]: * %File.Error{reason: nil, path: nil, action: ""}
2024-08-14T10:22:35.416631+02:00 bremen2 animina[460865]:   (mogrify 0.9.3) lib/mogrify.ex:13: Mogrify.open/1
2024-08-14T10:22:35.416651+02:00 bremen2 animina[460865]:   (animina 20240814.11014.107) lib/animina/accounts/resources/photo.ex:276: Animina.Accounts.Photo.resize_image/3
2024-08-14T10:22:35.416673+02:00 bremen2 animina[460865]:   (animina 20240814.11014.107) lib/animina/accounts/resources/photo.ex:266: anonymous fn/2 in Animina.Accounts.Photo.resize_image/1
2024-08-14T10:22:35.416723+02:00 bremen2 animina[460865]:   (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
2024-08-14T10:22:35.416784+02:00 bremen2 animina[460865]:   (animina 20240814.11014.107) lib/animina/accounts/resources/photo.ex:177: Animina.Accounts.Photo.change_after_action_0_generated_F26C32F8FCFF0724F6DFDB031FDE6017/3
2024-08-14T10:22:35.416845+02:00 bremen2 animina[460865]:   (ash 3.3.3) lib/ash/changeset/changeset.ex:3666: anonymous fn/2 in Ash.Changeset.run_after_actions/3
2024-08-14T10:22:35.416909+02:00 bremen2 animina[460865]:   (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
2024-08-14T10:22:35.416962+02:00 bremen2 animina[460865]:   (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
2024-08-14T10:22:35.417016+02:00 bremen2 animina[460865]:     (mogrify 0.9.3) lib/mogrify.ex:13: Mogrify.open/1
2024-08-14T10:22:35.417069+02:00 bremen2 animina[460865]:     (animina 20240814.11014.107) lib/animina/accounts/resources/photo.ex:276: Animina.Accounts.Photo.resize_image/3
2024-08-14T10:22:35.417129+02:00 bremen2 animina[460865]:     (animina 20240814.11014.107) lib/animina/accounts/resources/photo.ex:266: anonymous fn/2 in Animina.Accounts.Photo.resize_image/1
2024-08-14T10:22:35.417190+02:00 bremen2 animina[460865]:     (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
2024-08-14T10:22:35.417252+02:00 bremen2 animina[460865]:     (animina 20240814.11014.107) lib/animina/accounts/resources/photo.ex:177: Animina.Accounts.Photo.change_after_action_0_generated_F26C32F8FCFF0724F6DFDB031FDE6017/3
2024-08-14T10:22:35.417326+02:00 bremen2 animina[460865]:     (ash 3.3.3) lib/ash/changeset/changeset.ex:3666: anonymous fn/2 in Ash.Changeset.run_after_actions/3
2024-08-14T10:22:35.417386+02:00 bremen2 animina[460865]:     (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
2024-08-14T10:22:35.417440+02:00 bremen2 animina[460865]:     (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
2024-08-14T10:22:35.417507+02:00 bremen2 animina[460865]: Last message: %Phoenix.Socket.Message{topic: "lv:phx-F-uKpN3ycfGc7geC", event: "event", payload: %{"event" => "submit_photo", "type" => "form", "value" => "photo%5Buser_id%5D=0f6a135e-d299-422d-bcaf-6b9ac19a4f67&photo%5Bfilename%5D=67d2303e-c668-4217-8b9e-5c75b63c0261.jpg&photo%5Boriginal_filename%5D=IMG_8927.jpeg&photo%5Bext%5D=jpg&photo%5Bmime%5D=image%2Fjpeg&photo%5Bsize%5D=2771554"}, ref: "107", join_ref: "12"}
```

Why don't we get a proper error here?

@MICHAELMUNAVU83 Where in our code will this be triggered?

```elixir
2024-08-14T10:22:35.416580+02:00 bremen2 animina[460865]: ** (Ash.Error.Unknown) Unknown Error
2024-08-14T10:22:35.416611+02:00 bremen2 animina[460865]: * %File.Error{reason: nil, path: nil, action: ""}
```

I would like to debug this manually on the server but I don't know which part of our code triggers the problem.

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 Where is a proper logging of an error here?

```elixir
  defp copy_image(file_name, type) do
    case File.cp!(
           "priv/static/uploads/" <> file_name,
           "priv/static/uploads/optimized/#{type}/#{file_name}"
         ) do
      :ok -> "/uploads/optimized/#{type}/#{file_name}"
      _ -> "/uploads/optimized/#{type}/#{file_name}"
    end
  end
```

**Comment by MICHAELMUNAVU83** [comment]
Let me make a push for it

**Comment by wintermeyer** [comment]
I fixed it. WOW that took for ever to debug!

My bad. I should have started the deployment to production earlier. I am old enough to know that this is tricky.
