### ISSUE TITLE
no route found for GET /assets/app.js

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#864]
When I start the developement system with `iex -S mix phx.server` and open http://localhost:4000 I get this error:

```elixir
[info] GET /assets/app.js
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /assets/app.js (AniminaWeb.Router)
    (animina 0.2.0) deps/phoenix/lib/phoenix/router.ex:541: AniminaWeb.Router.call/2
    (animina 0.2.0) lib/animina_web/endpoint.ex:1: AniminaWeb.Endpoint.plug_builder_call/2
    (animina 0.2.0) deps/plug/lib/plug/debugger.ex:136: AniminaWeb.Endpoint."call (overridable 3)"/2
    (animina 0.2.0) lib/animina_web/endpoint.ex:1: AniminaWeb.Endpoint.call/2
    (phoenix 1.7.14) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (plug_cowboy 2.7.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
    (cowboy 2.12.0) /Users/stefan/GitHub/animina/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.12.0) /Users/stefan/GitHub/animina/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.12.0) /Users/stefan/GitHub/animina/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

<img width="1186" alt="Bildschirmfoto 2024-08-13 um 11 38 55" src="https://github.com/user-attachments/assets/020cd530-1a4e-4894-a819-c3a6fa5e7686">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , install dependancies and give it a go

```
cd assets
npm i
```

**Comment by wintermeyer** [comment]
How many times do I have to fall into that trap?! 🤦‍♂️
